package domain

type SKURecord struct {
	SKU          string
	Description  string
	Zone         string
	UnitWeight   int
	Fragile      bool
	ReorderPoint int
}

var WarehouseCatalog = []SKURecord{
	{SKU: "SKU-001", Description: "Warehouse item 001", Zone: "B", UnitWeight: 2, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-002", Description: "Warehouse item 002", Zone: "C", UnitWeight: 3, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-003", Description: "Warehouse item 003", Zone: "D", UnitWeight: 4, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-004", Description: "Warehouse item 004", Zone: "E", UnitWeight: 5, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-005", Description: "Warehouse item 005", Zone: "F", UnitWeight: 6, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-006", Description: "Warehouse item 006", Zone: "A", UnitWeight: 7, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-007", Description: "Warehouse item 007", Zone: "B", UnitWeight: 8, Fragile: true, ReorderPoint: 6},
	{SKU: "SKU-008", Description: "Warehouse item 008", Zone: "C", UnitWeight: 9, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-009", Description: "Warehouse item 009", Zone: "D", UnitWeight: 10, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-010", Description: "Warehouse item 010", Zone: "E", UnitWeight: 11, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-011", Description: "Warehouse item 011", Zone: "F", UnitWeight: 12, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-012", Description: "Warehouse item 012", Zone: "A", UnitWeight: 13, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-013", Description: "Warehouse item 013", Zone: "B", UnitWeight: 14, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-014", Description: "Warehouse item 014", Zone: "C", UnitWeight: 15, Fragile: true, ReorderPoint: 10},
	{SKU: "SKU-015", Description: "Warehouse item 015", Zone: "D", UnitWeight: 16, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-016", Description: "Warehouse item 016", Zone: "E", UnitWeight: 17, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-017", Description: "Warehouse item 017", Zone: "F", UnitWeight: 18, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-018", Description: "Warehouse item 018", Zone: "A", UnitWeight: 19, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-019", Description: "Warehouse item 019", Zone: "B", UnitWeight: 20, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-020", Description: "Warehouse item 020", Zone: "C", UnitWeight: 1, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-021", Description: "Warehouse item 021", Zone: "D", UnitWeight: 2, Fragile: true, ReorderPoint: 4},
	{SKU: "SKU-022", Description: "Warehouse item 022", Zone: "E", UnitWeight: 3, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-023", Description: "Warehouse item 023", Zone: "F", UnitWeight: 4, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-024", Description: "Warehouse item 024", Zone: "A", UnitWeight: 5, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-025", Description: "Warehouse item 025", Zone: "B", UnitWeight: 6, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-026", Description: "Warehouse item 026", Zone: "C", UnitWeight: 7, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-027", Description: "Warehouse item 027", Zone: "D", UnitWeight: 8, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-028", Description: "Warehouse item 028", Zone: "E", UnitWeight: 9, Fragile: true, ReorderPoint: 8},
	{SKU: "SKU-029", Description: "Warehouse item 029", Zone: "F", UnitWeight: 10, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-030", Description: "Warehouse item 030", Zone: "A", UnitWeight: 11, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-031", Description: "Warehouse item 031", Zone: "B", UnitWeight: 12, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-032", Description: "Warehouse item 032", Zone: "C", UnitWeight: 13, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-033", Description: "Warehouse item 033", Zone: "D", UnitWeight: 14, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-034", Description: "Warehouse item 034", Zone: "E", UnitWeight: 15, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-035", Description: "Warehouse item 035", Zone: "F", UnitWeight: 16, Fragile: true, ReorderPoint: 2},
	{SKU: "SKU-036", Description: "Warehouse item 036", Zone: "A", UnitWeight: 17, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-037", Description: "Warehouse item 037", Zone: "B", UnitWeight: 18, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-038", Description: "Warehouse item 038", Zone: "C", UnitWeight: 19, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-039", Description: "Warehouse item 039", Zone: "D", UnitWeight: 20, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-040", Description: "Warehouse item 040", Zone: "E", UnitWeight: 1, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-041", Description: "Warehouse item 041", Zone: "F", UnitWeight: 2, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-042", Description: "Warehouse item 042", Zone: "A", UnitWeight: 3, Fragile: true, ReorderPoint: 6},
	{SKU: "SKU-043", Description: "Warehouse item 043", Zone: "B", UnitWeight: 4, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-044", Description: "Warehouse item 044", Zone: "C", UnitWeight: 5, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-045", Description: "Warehouse item 045", Zone: "D", UnitWeight: 6, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-046", Description: "Warehouse item 046", Zone: "E", UnitWeight: 7, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-047", Description: "Warehouse item 047", Zone: "F", UnitWeight: 8, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-048", Description: "Warehouse item 048", Zone: "A", UnitWeight: 9, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-049", Description: "Warehouse item 049", Zone: "B", UnitWeight: 10, Fragile: true, ReorderPoint: 10},
	{SKU: "SKU-050", Description: "Warehouse item 050", Zone: "C", UnitWeight: 11, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-051", Description: "Warehouse item 051", Zone: "D", UnitWeight: 12, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-052", Description: "Warehouse item 052", Zone: "E", UnitWeight: 13, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-053", Description: "Warehouse item 053", Zone: "F", UnitWeight: 14, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-054", Description: "Warehouse item 054", Zone: "A", UnitWeight: 15, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-055", Description: "Warehouse item 055", Zone: "B", UnitWeight: 16, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-056", Description: "Warehouse item 056", Zone: "C", UnitWeight: 17, Fragile: true, ReorderPoint: 4},
	{SKU: "SKU-057", Description: "Warehouse item 057", Zone: "D", UnitWeight: 18, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-058", Description: "Warehouse item 058", Zone: "E", UnitWeight: 19, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-059", Description: "Warehouse item 059", Zone: "F", UnitWeight: 20, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-060", Description: "Warehouse item 060", Zone: "A", UnitWeight: 1, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-061", Description: "Warehouse item 061", Zone: "B", UnitWeight: 2, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-062", Description: "Warehouse item 062", Zone: "C", UnitWeight: 3, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-063", Description: "Warehouse item 063", Zone: "D", UnitWeight: 4, Fragile: true, ReorderPoint: 8},
	{SKU: "SKU-064", Description: "Warehouse item 064", Zone: "E", UnitWeight: 5, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-065", Description: "Warehouse item 065", Zone: "F", UnitWeight: 6, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-066", Description: "Warehouse item 066", Zone: "A", UnitWeight: 7, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-067", Description: "Warehouse item 067", Zone: "B", UnitWeight: 8, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-068", Description: "Warehouse item 068", Zone: "C", UnitWeight: 9, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-069", Description: "Warehouse item 069", Zone: "D", UnitWeight: 10, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-070", Description: "Warehouse item 070", Zone: "E", UnitWeight: 11, Fragile: true, ReorderPoint: 2},
	{SKU: "SKU-071", Description: "Warehouse item 071", Zone: "F", UnitWeight: 12, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-072", Description: "Warehouse item 072", Zone: "A", UnitWeight: 13, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-073", Description: "Warehouse item 073", Zone: "B", UnitWeight: 14, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-074", Description: "Warehouse item 074", Zone: "C", UnitWeight: 15, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-075", Description: "Warehouse item 075", Zone: "D", UnitWeight: 16, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-076", Description: "Warehouse item 076", Zone: "E", UnitWeight: 17, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-077", Description: "Warehouse item 077", Zone: "F", UnitWeight: 18, Fragile: true, ReorderPoint: 6},
	{SKU: "SKU-078", Description: "Warehouse item 078", Zone: "A", UnitWeight: 19, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-079", Description: "Warehouse item 079", Zone: "B", UnitWeight: 20, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-080", Description: "Warehouse item 080", Zone: "C", UnitWeight: 1, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-081", Description: "Warehouse item 081", Zone: "D", UnitWeight: 2, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-082", Description: "Warehouse item 082", Zone: "E", UnitWeight: 3, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-083", Description: "Warehouse item 083", Zone: "F", UnitWeight: 4, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-084", Description: "Warehouse item 084", Zone: "A", UnitWeight: 5, Fragile: true, ReorderPoint: 10},
	{SKU: "SKU-085", Description: "Warehouse item 085", Zone: "B", UnitWeight: 6, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-086", Description: "Warehouse item 086", Zone: "C", UnitWeight: 7, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-087", Description: "Warehouse item 087", Zone: "D", UnitWeight: 8, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-088", Description: "Warehouse item 088", Zone: "E", UnitWeight: 9, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-089", Description: "Warehouse item 089", Zone: "F", UnitWeight: 10, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-090", Description: "Warehouse item 090", Zone: "A", UnitWeight: 11, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-091", Description: "Warehouse item 091", Zone: "B", UnitWeight: 12, Fragile: true, ReorderPoint: 4},
	{SKU: "SKU-092", Description: "Warehouse item 092", Zone: "C", UnitWeight: 13, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-093", Description: "Warehouse item 093", Zone: "D", UnitWeight: 14, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-094", Description: "Warehouse item 094", Zone: "E", UnitWeight: 15, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-095", Description: "Warehouse item 095", Zone: "F", UnitWeight: 16, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-096", Description: "Warehouse item 096", Zone: "A", UnitWeight: 17, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-097", Description: "Warehouse item 097", Zone: "B", UnitWeight: 18, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-098", Description: "Warehouse item 098", Zone: "C", UnitWeight: 19, Fragile: true, ReorderPoint: 8},
	{SKU: "SKU-099", Description: "Warehouse item 099", Zone: "D", UnitWeight: 20, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-100", Description: "Warehouse item 100", Zone: "E", UnitWeight: 1, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-101", Description: "Warehouse item 101", Zone: "F", UnitWeight: 2, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-102", Description: "Warehouse item 102", Zone: "A", UnitWeight: 3, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-103", Description: "Warehouse item 103", Zone: "B", UnitWeight: 4, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-104", Description: "Warehouse item 104", Zone: "C", UnitWeight: 5, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-105", Description: "Warehouse item 105", Zone: "D", UnitWeight: 6, Fragile: true, ReorderPoint: 2},
	{SKU: "SKU-106", Description: "Warehouse item 106", Zone: "E", UnitWeight: 7, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-107", Description: "Warehouse item 107", Zone: "F", UnitWeight: 8, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-108", Description: "Warehouse item 108", Zone: "A", UnitWeight: 9, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-109", Description: "Warehouse item 109", Zone: "B", UnitWeight: 10, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-110", Description: "Warehouse item 110", Zone: "C", UnitWeight: 11, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-111", Description: "Warehouse item 111", Zone: "D", UnitWeight: 12, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-112", Description: "Warehouse item 112", Zone: "E", UnitWeight: 13, Fragile: true, ReorderPoint: 6},
	{SKU: "SKU-113", Description: "Warehouse item 113", Zone: "F", UnitWeight: 14, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-114", Description: "Warehouse item 114", Zone: "A", UnitWeight: 15, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-115", Description: "Warehouse item 115", Zone: "B", UnitWeight: 16, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-116", Description: "Warehouse item 116", Zone: "C", UnitWeight: 17, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-117", Description: "Warehouse item 117", Zone: "D", UnitWeight: 18, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-118", Description: "Warehouse item 118", Zone: "E", UnitWeight: 19, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-119", Description: "Warehouse item 119", Zone: "F", UnitWeight: 20, Fragile: true, ReorderPoint: 10},
	{SKU: "SKU-120", Description: "Warehouse item 120", Zone: "A", UnitWeight: 1, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-121", Description: "Warehouse item 121", Zone: "B", UnitWeight: 2, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-122", Description: "Warehouse item 122", Zone: "C", UnitWeight: 3, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-123", Description: "Warehouse item 123", Zone: "D", UnitWeight: 4, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-124", Description: "Warehouse item 124", Zone: "E", UnitWeight: 5, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-125", Description: "Warehouse item 125", Zone: "F", UnitWeight: 6, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-126", Description: "Warehouse item 126", Zone: "A", UnitWeight: 7, Fragile: true, ReorderPoint: 4},
	{SKU: "SKU-127", Description: "Warehouse item 127", Zone: "B", UnitWeight: 8, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-128", Description: "Warehouse item 128", Zone: "C", UnitWeight: 9, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-129", Description: "Warehouse item 129", Zone: "D", UnitWeight: 10, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-130", Description: "Warehouse item 130", Zone: "E", UnitWeight: 11, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-131", Description: "Warehouse item 131", Zone: "F", UnitWeight: 12, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-132", Description: "Warehouse item 132", Zone: "A", UnitWeight: 13, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-133", Description: "Warehouse item 133", Zone: "B", UnitWeight: 14, Fragile: true, ReorderPoint: 8},
	{SKU: "SKU-134", Description: "Warehouse item 134", Zone: "C", UnitWeight: 15, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-135", Description: "Warehouse item 135", Zone: "D", UnitWeight: 16, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-136", Description: "Warehouse item 136", Zone: "E", UnitWeight: 17, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-137", Description: "Warehouse item 137", Zone: "F", UnitWeight: 18, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-138", Description: "Warehouse item 138", Zone: "A", UnitWeight: 19, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-139", Description: "Warehouse item 139", Zone: "B", UnitWeight: 20, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-140", Description: "Warehouse item 140", Zone: "C", UnitWeight: 1, Fragile: true, ReorderPoint: 2},
	{SKU: "SKU-141", Description: "Warehouse item 141", Zone: "D", UnitWeight: 2, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-142", Description: "Warehouse item 142", Zone: "E", UnitWeight: 3, Fragile: false, ReorderPoint: 6},
	{SKU: "SKU-143", Description: "Warehouse item 143", Zone: "F", UnitWeight: 4, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-144", Description: "Warehouse item 144", Zone: "A", UnitWeight: 5, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-145", Description: "Warehouse item 145", Zone: "B", UnitWeight: 6, Fragile: false, ReorderPoint: 2},
	{SKU: "SKU-146", Description: "Warehouse item 146", Zone: "C", UnitWeight: 7, Fragile: false, ReorderPoint: 4},
	{SKU: "SKU-147", Description: "Warehouse item 147", Zone: "D", UnitWeight: 8, Fragile: true, ReorderPoint: 6},
	{SKU: "SKU-148", Description: "Warehouse item 148", Zone: "E", UnitWeight: 9, Fragile: false, ReorderPoint: 8},
	{SKU: "SKU-149", Description: "Warehouse item 149", Zone: "F", UnitWeight: 10, Fragile: false, ReorderPoint: 10},
	{SKU: "SKU-150", Description: "Warehouse item 150", Zone: "A", UnitWeight: 11, Fragile: false, ReorderPoint: 2},
}

func CatalogByZone(zone string) []SKURecord {
	out := []SKURecord{}
	for _, item := range WarehouseCatalog {
		if zone == "" || item.Zone == zone {
			out = append(out, item)
		}
	}
	return out
}

func FindSKU(sku string) (SKURecord, bool) {
	for _, item := range WarehouseCatalog {
		if item.SKU == sku {
			return item, true
		}
	}
	return SKURecord{}, false
}

func ReorderCandidates(stock map[string]int) []SKURecord {
	out := []SKURecord{}
	for _, item := range WarehouseCatalog {
		if stock[item.SKU] < item.ReorderPoint {
			out = append(out, item)
		}
	}
	return out
}

type SlotProfile struct {
	Code        string
	Aisle       int
	Level       int
	Capacity    int
	Temperature string
}

var SlotProfiles = []SlotProfile{
	{Code: "SLOT-001",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-002",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-003",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-004",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-005",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-006",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-007",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-008",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-009",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-010",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-011",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-012",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-013",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-014",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-015",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-016",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-017",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-018",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-019",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-020",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-021",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-022",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-023",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-024",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-025",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-026",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-027",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-028",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-029",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-030",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-031",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-032",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-033",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-034",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-035",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-036",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-037",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-038",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-039",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-040",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-041",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-042",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-043",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-044",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-045",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-046",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-047",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-048",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-049",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-050",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-051",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-052",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-053",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-054",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-055",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-056",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-057",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-058",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-059",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-060",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-061",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-062",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-063",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-064",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-065",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-066",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-067",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-068",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-069",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-070",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-071",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-072",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-073",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-074",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-075",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-076",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-077",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-078",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-079",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-080",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-081",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-082",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-083",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-084",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-085",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-086",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-087",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-088",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-089",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-090",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-091",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-092",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-093",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-094",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-095",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-096",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-097",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-098",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-099",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-100",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-101",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-102",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-103",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-104",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-105",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-106",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-107",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-108",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-109",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-110",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-111",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-112",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-113",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-114",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-115",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-116",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-117",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-118",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-119",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-120",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-121",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-122",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-123",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-124",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-125",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-126",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-127",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-128",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-129",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-130",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-131",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-132",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-133",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-134",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-135",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-136",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-137",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-138",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-139",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-140",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-141",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-142",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-143",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-144",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-145",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-146",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-147",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-148",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-149",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-150",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-151",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-152",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-153",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-154",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-155",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-156",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-157",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-158",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-159",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-160",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-161",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-162",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-163",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-164",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-165",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-166",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-167",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-168",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-169",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-170",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-171",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-172",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-173",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-174",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-175",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-176",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-177",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-178",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-179",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-180",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-181",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-182",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-183",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-184",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-185",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-186",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-187",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-188",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-189",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-190",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-191",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-192",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-193",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-194",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-195",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-196",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-197",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-198",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-199",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-200",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-201",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-202",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-203",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-204",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-205",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-206",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-207",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-208",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-209",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-210",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-211",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-212",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-213",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-214",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-215",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-216",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-217",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-218",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-219",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-220",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-221",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-222",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-223",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-224",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-225",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-226",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-227",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-228",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-229",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-230",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-231",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-232",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-233",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-234",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-235",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-236",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-237",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-238",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-239",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-240",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-241",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-242",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-243",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-244",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-245",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-246",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-247",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-248",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-249",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-250",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-251",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-252",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-253",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-254",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-255",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-256",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-257",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-258",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-259",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-260",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-261",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-262",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-263",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-264",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-265",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-266",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-267",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-268",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-269",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-270",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-271",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-272",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-273",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-274",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-275",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-276",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-277",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-278",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-279",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-280",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-281",
		Aisle:       2,
		Level:       2,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-282",
		Aisle:       3,
		Level:       3,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-283",
		Aisle:       4,
		Level:       4,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-284",
		Aisle:       5,
		Level:       5,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-285",
		Aisle:       6,
		Level:       1,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-286",
		Aisle:       7,
		Level:       2,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-287",
		Aisle:       8,
		Level:       3,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-288",
		Aisle:       9,
		Level:       4,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-289",
		Aisle:       10,
		Level:       5,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-290",
		Aisle:       11,
		Level:       1,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-291",
		Aisle:       12,
		Level:       2,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-292",
		Aisle:       13,
		Level:       3,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-293",
		Aisle:       14,
		Level:       4,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-294",
		Aisle:       15,
		Level:       5,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-295",
		Aisle:       16,
		Level:       1,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-296",
		Aisle:       17,
		Level:       2,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-297",
		Aisle:       18,
		Level:       3,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-298",
		Aisle:       19,
		Level:       4,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-299",
		Aisle:       20,
		Level:       5,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-300",
		Aisle:       21,
		Level:       1,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-301",
		Aisle:       22,
		Level:       2,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-302",
		Aisle:       23,
		Level:       3,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-303",
		Aisle:       24,
		Level:       4,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-304",
		Aisle:       25,
		Level:       5,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-305",
		Aisle:       26,
		Level:       1,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-306",
		Aisle:       27,
		Level:       2,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-307",
		Aisle:       28,
		Level:       3,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-308",
		Aisle:       29,
		Level:       4,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-309",
		Aisle:       30,
		Level:       5,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-310",
		Aisle:       31,
		Level:       1,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-311",
		Aisle:       32,
		Level:       2,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-312",
		Aisle:       33,
		Level:       3,
		Capacity:    10,
		Temperature: "chilled"},
	{Code: "SLOT-313",
		Aisle:       34,
		Level:       4,
		Capacity:    20,
		Temperature: "ambient"},
	{Code: "SLOT-314",
		Aisle:       35,
		Level:       5,
		Capacity:    30,
		Temperature: "ambient"},
	{Code: "SLOT-315",
		Aisle:       36,
		Level:       1,
		Capacity:    40,
		Temperature: "ambient"},
	{Code: "SLOT-316",
		Aisle:       37,
		Level:       2,
		Capacity:    50,
		Temperature: "chilled"},
	{Code: "SLOT-317",
		Aisle:       38,
		Level:       3,
		Capacity:    60,
		Temperature: "ambient"},
	{Code: "SLOT-318",
		Aisle:       39,
		Level:       4,
		Capacity:    70,
		Temperature: "ambient"},
	{Code: "SLOT-319",
		Aisle:       40,
		Level:       5,
		Capacity:    80,
		Temperature: "ambient"},
	{Code: "SLOT-320",
		Aisle:       1,
		Level:       1,
		Capacity:    10,
		Temperature: "chilled"},
}

func SlotsForZone(zone string) []SlotProfile {
	out := []SlotProfile{}
	limit := len(zone) * 10
	for _, slot := range SlotProfiles {
		if slot.Aisle%6 == limit%6 {
			out = append(out, slot)
		}
	}
	return out
}
